[workspace]
resolver = "2"
members = [
    # beginner tutorials
    "code/beginner/*",
    # intermediate tutorials
    "code/intermediate/*",
    # showcase
    "code/showcase/*",
    "run-wasm",
]
exclude = [
    "code/showcase/imgui-demo",
    # "code/showcase/pong",
]

[workspace.package]
edition = "2021"
rust-version = "1.64"

[workspace.dependencies.image]
version = "0.24"
default-features = false

[workspace.dependencies.wgc]
package = "wgpu-core"
features = ["raw-window-handle"]
version = "0.15"

[workspace.dependencies]
app-surface = { git = "https://github.com/jinleili/wgpu-on-app", rev = "5c01ecc" }
# app-surface = { path = "../idroid/wgpu-in-app/app-surface" }
bytemuck = "1.4"
cfg-if = "1"
cgmath = "0.18"
glam = "0.22"
env_logger = "0.9"
futures-intrusive = "0.4"
instant = "0.1"
log = "0.4"
naga = { version = "0.10" }
pollster = "0.2"
rayon = "1.4"
tobj = "3.2"
winit = "0.27.1"
wgpu = { version = "0.15", default-features = false }

# wasm32 dependencies
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
js-sys = "0.3.60"
reqwest = { version = "0.11" }
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
web-sys = "0.3.60"

# build-dependencies
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"

[profile.release]
# lto = true # VERY slightly smaller wasm
# opt-level = 's' # 10-30% smaller wasm compared to `opt-level = 3`
# opt-level = 1 # very slow and big wasm. Don't do this.
opt-level = 2 # fast and small wasm, basically same as `opt-level = 's'`
# opt-level = 3 # unecessarily large wasm for no performance gain

# debug = true # include debug symbols, useful when profiling wasm
