[workspace]
resolver = "2"
members = [
    # beginner tutorials
    "code/beginner/*",

    # intermediate tutorials
    "code/intermediate/*",

    # showcase
    "code/showcase/*",

    "run-wasm"
]
exclude = [
    "code/showcase/imgui-demo"
    # "code/showcase/pong",
]

[workspace.package]
edition = "2021"
rust-version = "1.64"

[workspace.dependencies.image]
version = "0.24"
default-features = false

[workspace.dependencies]
app-surface = { git = "https://github.com/jinleili/wgpu-on-app", tag = "0.1.2" }
bytemuck = "1.4"
cfg-if = "1"
cgmath = "0.18"
env_logger = "0.9"
futures-intrusive = "0.4"
instant = "0.1"
log = "0.4"
naga = { version = "0.10" }
pollster = "0.2"
rayon = "1.4"
tobj = "3.2"
winit = "0.27.1"
wgpu = "0.14"

# wasm32 dependencies
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"
reqwest = { version = "0.11" }
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.30"
web-sys = "0.3.60"

# build-dependencies
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"
