[package]
name = "compute-pipeline"
version = "0.1.0"
authors = ["Jinlei Li <jinleili0@outlook.com>"]
edition.workspace = true
rust-version.workspace = true

[dependencies]
# app-surface.workspace = true
app-surface = { git = "https://github.com/jinleili/wgpu-on-app", branch = "wgpu_trunk"}
# app-surface = { path = "../../../../idroid/wgpu-in-app/app-surface" }
bytemuck.workspace = true
cfg-if.workspace = true
env_logger.workspace = true
log.workspace = true
pollster.workspace = true
winit.workspace = true
# wgpu.workspace = true
# wgpu = "0.15"
wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "cfc038ae" }
png = "0.17"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace = true
console_log.workspace = true
js-sys.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = ["Document", "Window", "Element"] }
